### ISSUE TITLE
Swift 3 in the works?

### ISSUE THREAD

**Issue by oliverbytes** [thellimist/EZAlertController#12]
Hi thellimist,

just wondering if you're still working on this project and to upgrade it to work with Swift 3? I use your lib a lot and it's very helpful. Thanks a lot for the great work.

**Comment by thellimist** [comment]
Hi @NemOry 

The only PR I got related with Swift3 is https://github.com/thellimist/EZAlertController/pull/11.

You can try it out. If it doesn't work feel free to send a PR 😉

**Comment by LeandroHub** [comment]
Hi! Thanks for this library. I'm using Xcode 8 and Swift 3.0 and I'm getting like 15 errors for EZAlertController.swift. Is that possible? I'm using the latest release. 

Thanks!

**Comment by thellimist** [comment]
I'll be updating swift 3 support this weekend.

**Comment by LeandroHub** [comment]
Awesome! Thanks!

**Comment by nrdgroove** [comment]
Any news about this?

**Comment by thellimist** [comment]
Hi @malakiya, 

Thanks for following up. I didn't have time in the weekend. I'll work on it whenever I've spare time.

**Comment by thellimist** [comment]
Updated for Swift 3.0

https://github.com/thellimist/EZAlertController/releases/tag/3.1

**Comment by nrdgroove** [comment]
Thanks!
