### ISSUE TITLE
How to show actionsheet on iPad?

### ISSUE THREAD

**Issue by yuchaozh** [thellimist/EZAlertController#13]
I use the demo code to show the actionsheet. It shows on iPhone but not show on iPad.

**Comment by thellimist** [comment]
Sorry for late reply.

All of my apps are for iPhone so I didn't try it on iPad. The code is simple you can make a pull request to support on iPad.

Thanks

**Comment by yuchaozh** [comment]
Finally, I find a way to enable show the actionsheet on iPad. You can close this issue. Thanks.

**Comment by thellimist** [comment]
If you can describe your solution for future users that'd be great.

Thanks

**Comment by SupaBasti** [comment]
I face the same issue on iPad. Anybody who solved that?

**Comment by stackwares** [comment]
I am facing the same issue, it doesn't work for the iPad. what's the solution please?

**Comment by oliverbytes** [comment]
Hi guys. How to fix the issue on the iPad? I'm using the latest EZAlertController version. It works on the iPhone but on the iPad no.

**Comment by oliverbytes** [comment]
Error

Your application has presented a UIActivityViewController In its current trait environment, the modalPresentationStyle of a UIActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
