### ISSUE TITLE
Set Tint Color?

### ISSUE THREAD

**Issue by oliverbytes** [thellimist/EZAlertController#20]
Hi guys, how do we set the Tint Color of the overall dialog in this awesome pod?

**Comment by thellimist** [comment]
This is a simple function template. Every single function provided in this pod is returning the `UIAlertController` object. You can change anything which `UIAlertController` allows you to change 

```
    open class func alert(_ title: String) -> UIAlertController {
        return alert(title, message: "")
    }
```

for tint color check [this](http://stackoverflow.com/questions/32693369/uialertcontroller-tint-color-defaults-to-blue-on-highlight) link

```
let myAlert = EZAlertController.alert("hey")
// do whatever you want with myAlert
```
