### ISSUE TITLE
Build Error with XCode 8.1

### ISSUE THREAD

**Issue by benaneesh** [thellimist/EZAlertController#22]
On version 3.1 and I get this error with xcode 8.1:

<img width="728" alt="screen shot 2016-11-01 at 10 46 05 am" src="https://cloud.githubusercontent.com/assets/1724896/19900407/9e3b53c0-a020-11e6-8aef-039c9f91cc5c.png">

Should it be `self.init(title: title, style: preferredStyle)` ?

**Comment by floriangbh** [comment]
https://github.com/thellimist/EZAlertController/pull/21/files

**Comment by thellimist** [comment]
https://github.com/thellimist/EZAlertController/releases/tag/3.2

Thanks!
