### ISSUE TITLE
Using EZAlertController in Objective-C code

### ISSUE THREAD

**Issue by ShadeApps** [thellimist/EZAlertController#25]
I'm wondering if it's possible to use this fabulous control in legacy Objective-C code alongside Swift classes?

Other Swift code works fine for me, but EZAlertController is somehow not recognized

<img width="430" alt="ezalert" src="https://cloud.githubusercontent.com/assets/2706049/21887228/25560976-d8d0-11e6-83bc-d2bea92ca9fb.png">

P.S. Thanks for really nice and useful control!

**Comment by thellimist** [comment]
@goktugyil do you know if this is possible?

**Comment by Esqarrouth** [comment]
I've haven't been using ObjC in years, so not idea. Maybe its somehow not importing in the project correctly.

**Comment by ShadeApps** [comment]
It has nothing to do with importing code as other Swift classes and files work in this very controller. I'll try to look into it myself and maybe create a PR for Obj-C support as it may prove useful
